name = "golddydev/raiders-validator"
version = "0.0.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'golddydev/raiders-validator'"

[repository]
user = "golddydev"
project = "raiders-validator"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "logical-mechanism/assist"
version = "v0.5.1"
source = "github"

[config]
